### ISSUE TITLE
SSF

### ISSUE THREAD

**Issue by jcp101** [peterantkowiak/SSF-workflow#1]
Hi, I stumbled across your instructions on how to perform SSFs in R and they have worked up until the extraction of rasters. When I plot my raster files I can see them clearly but when I go to extract them e.g
`woods.extr <- extract(woods, F108.steps.spdf,
                           method='simple',sp=F, df=T)`

I get something that looks like this         
           ID WOODSRASTER
1         1          NA

Which then continues for the rest of the code - all rasters have NA describing them. I was wondering whether someone could help me with this problem at all?

**Comment by peterantkowiak** [comment]
Hi @jcp101! Nice that you found this and actually tried to use it! The code is not maintained on a regular basis but I might still be able to help you if you paste the output of `str(woods)` and `str(F108.steps.spdf)`.

**Comment by jcp101** [comment]
Hi there, yes well I've been searching for something similar for a while now as I really cannot get to grips with GME! I think my problem may be more GIS related than R related (am very much a newbie at using it so struggling quite a bit!). I think my problem is in creating a raster file which defines presence/absence of woodland - I created polygons of woodland and then of open areas, and converted this shapefile into a raster, but I don't think I'm doing it right.... Here is my output (the name has changed from woods to open) 

`> str(open)
Formal class 'RasterLayer' [package "raster"] with 12 slots
  ..@ file    :Formal class '.RasterFile' [package "raster"] with 13 slots
  .. .. ..@ name        : chr "C:\\Users\\labuser\\Documents\\GPS\\Jess GPS data\\USEABLE TRACKS\\108\\OPENCLOSE_PolygonToRaster2.tif"
  .. .. ..@ datanotation: chr "INT1U"
  .. .. ..@ byteorder   : chr "little"
  .. .. ..@ nodatavalue : num -Inf
  .. .. ..@ NAchanged   : logi FALSE
  .. .. ..@ nbands      : int 1
  .. .. ..@ bandorder   : chr "BIL"
  .. .. ..@ offset      : int 0
  .. .. ..@ toptobottom : logi TRUE
  .. .. ..@ blockrows   : int 128
  .. .. ..@ blockcols   : int 128
  .. .. ..@ driver      : chr "gdal"
  .. .. ..@ open        : logi FALSE
  ..@ data    :Formal class '.SingleLayerData' [package "raster"] with 13 slots
  .. .. ..@ values    : logi(0) 
  .. .. ..@ offset    : num 0
  .. .. ..@ gain      : num 1
  .. .. ..@ inmemory  : logi FALSE
  .. .. ..@ fromdisk  : logi TRUE
  .. .. ..@ isfactor  : logi TRUE
  .. .. ..@ attributes:List of 1
  .. .. .. ..$ :'data.frame':	2 obs. of  4 variables:
  .. .. .. .. ..$ ID      : int [1:2] 0 1
  .. .. .. .. ..$ OBJECTID: int [1:2] 1 2
  .. .. .. .. ..$ Value   : int [1:2] 0 1
  .. .. .. .. ..$ Count   : num [1:2] 16720 58247
  .. .. ..@ haveminmax: logi TRUE
  .. .. ..@ min       : num 0
  .. .. ..@ max       : num 1
  .. .. ..@ band      : int 1
  .. .. ..@ unit      : chr ""
  .. .. ..@ names     : chr "OPENCLOSE_PolygonToRaster2"
  ..@ legend  :Formal class '.RasterLegend' [package "raster"] with 5 slots
  .. .. ..@ type      : chr(0) 
  .. .. ..@ values    : logi(0) 
  .. .. ..@ color     : logi(0) 
  .. .. ..@ names     : logi(0) 
  .. .. ..@ colortable: logi(0) 
  ..@ title   : chr(0) 
  ..@ extent  :Formal class 'Extent' [package "raster"] with 4 slots
  .. .. ..@ xmin: num -3.94
  .. .. ..@ xmax: num -3.93
  .. .. ..@ ymin: num 50.8
  .. .. ..@ ymax: num 50.8
  ..@ rotated : logi FALSE
  ..@ rotation:Formal class '.Rotation' [package "raster"] with 2 slots
  .. .. ..@ geotrans: num(0) 
  .. .. ..@ transfun:function ()  
  ..@ ncols   : int 440
  ..@ nrows   : int 244
  ..@ crs     :Formal class 'CRS' [package "sp"] with 1 slot
  .. .. ..@ projargs: chr "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
  ..@ history : list()
  ..@ z       : list()
> str(F108.steps.spdf)
Formal class 'SpatialPointsDataFrame' [package "sp"] with 5 slots
  ..@ data       :'data.frame':	15342 obs. of  18 variables:
  .. ..$ x        : num [1:15342] 50.8 50.8 50.8 50.8 50.8 ...
  .. ..$ y        : num [1:15342] -3.93 -3.93 -3.93 -3.93 -3.93 ...
  .. ..$ date     : POSIXct[1:15342], format: "2017-06-12 12:25:01" ...
  .. ..$ dx       : num [1:15342] 3.10e-05 7.41e-06 -1.17e-05 2.42e-06 -6.81e-07 ...
  .. ..$ dy       : num [1:15342] 1.60e-05 4.24e-06 -1.03e-06 -5.93e-06 1.55e-05 ...
  .. ..$ dist     : num [1:15342] 3.49e-05 8.54e-06 1.17e-05 6.40e-06 1.55e-05 ...
  .. ..$ dt       : num [1:15342] 1 1 1 1 1 1 2 2 2 2 ...
  .. ..$ R2n      : num [1:15342] 8.5e-10 8.5e-10 8.5e-10 8.5e-10 8.5e-10 ...
  .. ..$ abs.angle: num [1:15342] 0.476 0.52 3.23 -1.184 1.615 ...
  .. ..$ rel.angle: num [1:15342] 0.0896 0.133 2.8429 -1.5708 1.2278 ...
  .. ..$ id       : Factor w/ 1 level "108": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ burst    : Factor w/ 1 level "108": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ pkey     : Factor w/ 55657 levels "108.2017-06-12 12:25:00",..: 2 2 2 2 2 2 3 3 3 3 ...
  .. ..$ case     : num [1:15342] 1 0 0 0 0 0 1 0 0 0 ...
  .. ..$ strata   : int [1:15342] 1 1 1 1 1 1 2 2 2 2 ...
  .. ..$ new_x    : num [1:15342] 50.8 50.8 50.8 50.8 50.8 ...
  .. ..$ new_y    : num [1:15342] -3.93 -3.93 -3.93 -3.93 -3.93 ...
  .. ..$ open     : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
  ..@ coords.nrs : num(0) 
  ..@ coords     : num [1:15342, 1:2] 50.8 50.8 50.8 50.8 50.8 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:15342] "108.2" "108.2.1" "108.2.2" "108.2.3" ...
  .. .. ..$ : chr [1:2] "new_x" "new_y"
  ..@ bbox       : num [1:2, 1:2] 50.77 -3.93 50.78 -3.93
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:2] "new_x" "new_y"
  .. .. ..$ : chr [1:2] "min" "max"
  ..@ proj4string:Formal class 'CRS' [package "sp"] with 1 slot
  .. .. ..@ projargs: chr NA`

**Comment by peterantkowiak** [comment]
Hi! Yes, it is rather a GIS than SSF problem. If you look at the coordinates slot of your `F108.steps.spdf`, you will notice that the x and y coordinates are mixed up. Your points end up in the Indian Ocean instead of Devon / UK and that's why all extracted values are NA. Hope this helps ;-)

**Comment by jcp101** [comment]
How incredibly silly of me, have fixed this now and all the NAs have gone, would be interesting if some of my birds had gone to the Indian ocean however! Will let you know how I get on with the code, your help is greatly appreciated!
